import pandas as pd
import matplotlib.pyplot as plt

dfTimer = pd.read_csv('operation-timer.csv')
dfNoTimer = pd.read_csv('operation-notimer.csv')


fig, axs = plt.subplots(2, 2)
fig.tight_layout(h_pad=4)

axs[0][0].plot(dfTimer['DIMENSION'], dfTimer['CREATION'], label='Creation')
axs[0][0].plot(dfTimer['DIMENSION_N'], dfTimer['ADD_NEW_KMER'], label='Add new kmer')
axs[0][0].plot(dfTimer['DIMENSION_E'], dfTimer['ADD_EXISTING_KMER'], label='Add existing kmer')
axs[0][0].plot(dfTimer['DIMENSION_M'], dfTimer['ADD_MIX_KMER'],  label='Add mix kmer')
axs[0][0].set_ylabel('Time [ms]')
axs[0][0].set_xlabel('Dimension [MB]')
axs[0][0].set_yscale('log')
axs[0][0].set_xscale('log')
axs[0][0].legend(loc=4)
axs[0][0].set_title('Operation - DS time')

axs[1][0].plot(dfTimer['DIMENSION'], dfTimer['MEM_CREATION'], label='Creation')
axs[1][0].plot(dfTimer['DIMENSION_N'], dfTimer['MEM_ADD_N'],  label='Add new kmer')
axs[1][0].plot( dfTimer['DIMENSION_E'], dfTimer['MEM_ADD_E'], label='Add existing kmer')
axs[1][0].plot( dfTimer['DIMENSION_M'], dfTimer['MEM_ADD_M'], label='Add mix kmer')
axs[1][0].set_ylabel('Maximum resident set size [KByte]')
axs[1][0].set_xlabel('Dimension [MB]')
axs[1][0].set_yscale('log')
axs[1][0].set_xscale('log')
axs[1][0].legend(loc=4)
axs[1][0].set_title('Operation - DS time')

axs[0][1].plot(dfNoTimer['DIMENSION'], dfNoTimer['CREATION'],  label='Creation')
axs[0][1].plot(dfNoTimer['DIMENSION_N'], dfNoTimer['ADD_NEW_KMER'],  label='Add new kmer')
axs[0][1].plot(dfNoTimer['DIMENSION_E'], dfNoTimer['ADD_EXISTING_KMER'], label='Add existing kmer')
axs[0][1].plot( dfNoTimer['DIMENSION_M'], dfNoTimer['ADD_MIX_KMER'], label='Add mix kmer')
axs[0][1].set_ylabel('Time [ms]')
axs[0][1].set_xlabel('Dimension [MB]')
axs[0][1].set_yscale('log')
axs[0][1].set_xscale('log')
axs[0][1].legend(loc=4)
axs[0][1].set_title('Operation - Global time')

axs[1][1].plot(dfNoTimer['DIMENSION'],dfNoTimer['MEM_CREATION'],  label='Creation')
axs[1][1].plot(dfNoTimer['DIMENSION_N'], dfNoTimer['MEM_ADD_N'], label='Add new kmer')
axs[1][1].plot(dfNoTimer['DIMENSION_E'], dfNoTimer['MEM_ADD_E'], label='Add existing kmer')
axs[1][1].plot(dfNoTimer['DIMENSION_M'], dfNoTimer['MEM_ADD_M'], label='Add mix kmer')
axs[1][1].set_ylabel('Maximum resident set size [KByte]')
axs[1][1].set_xlabel('Dimension [MB]')
axs[1][1].set_xscale('log')
axs[1][1].set_yscale('log')
axs[1][1].legend(loc=4)
axs[1][1].set_title('Operation - Global time')

plt.show()